// <auto-generated />
namespace PrimeApps.Model.Migrations.TenantDB
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Task537 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Task537));
        
        string IMigrationMetadata.Id
        {
            get { return "201701111338462_Task537"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
