// <auto-generated />
namespace OfisimCRM.Model.Migrations.TenantDB
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Task1900 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Task1900));
        
        string IMigrationMetadata.Id
        {
            get { return "201805171359071_Task1900"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
