// <auto-generated />
namespace OfisimCRM.Model.Migrations.TenantDB
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Task1731 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Task1731));
        
        string IMigrationMetadata.Id
        {
            get { return "201805201435030_Task1731"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
