// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrimeApps.Model.Context;

namespace PrimeApps.Model.Migrations.TenantDB
{
    [DbContext(typeof(TenantDBContext))]
    [Migration("20190120072050_CoreInitial")]
    partial class CoreInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
