//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimeApps.App.Resources.Auth {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Authorization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Authorization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrimeApps.App.Resources.Auth.Resource", typeof(Authorization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid activation code..
        /// </summary>
        public static string ActivationError {
            get {
                return ResourceManager.GetString("ActivationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is activating. Please wait....
        /// </summary>
        public static string ActivationMessageFree {
            get {
                return ResourceManager.GetString("ActivationMessageFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create My Account.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking on &apos;Create My Account&apos; button, you agree to {0} and {1}.
        /// </summary>
        public static string CreateInfo {
            get {
                return ResourceManager.GetString("CreateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t have an account you can.
        /// </summary>
        public static string DontHaveAccount {
            get {
                return ResourceManager.GetString("DontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail you have chosen does not match your registered e-mail..
        /// </summary>
        public static string EmailNotMatchContent {
            get {
                return ResourceManager.GetString("EmailNotMatchContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail match problem..
        /// </summary>
        public static string EmailNotMatchTitle {
            get {
                return ResourceManager.GetString("EmailNotMatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string EN {
            get {
                return ResourceManager.GetString("EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred. Please try again later..
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your registered e-mail address. We&apos;ll send you the instructions to reset your password..
        /// </summary>
        public static string ForgotInfo {
            get {
                return ResourceManager.GetString("ForgotInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not activated..
        /// </summary>
        public static string ForgotNotActivated {
            get {
                return ResourceManager.GetString("ForgotNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user is found with this e-mail address..
        /// </summary>
        public static string ForgotNotFound {
            get {
                return ResourceManager.GetString("ForgotNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPass {
            get {
                return ResourceManager.GetString("ForgotPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your e-mail for a message from Ofisim.com then click on the link to change your password..
        /// </summary>
        public static string ForgotPasswordSuccess {
            get {
                return ResourceManager.GetString("ForgotPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password reset link has been sent.
        /// </summary>
        public static string ForgotPasswordSuccessTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the form below and start using your &lt;strong&gt;free trial with full of features for 15 days !&lt;/strong&gt;.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account? Sign-in..
        /// </summary>
        public static string HaveAccount {
            get {
                return ResourceManager.GetString("HaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid e-mail..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid phone number..
        /// </summary>
        public static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You tried to log in with your existing account to a different application..
        /// </summary>
        public static string IsNotValidAppContent {
            get {
                return ResourceManager.GetString("IsNotValidAppContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information does not match the application..
        /// </summary>
        public static string IsNotValidAppTitle {
            get {
                return ResourceManager.GetString("IsNotValidAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login to continue..
        /// </summary>
        public static string JoinSuccessMessage {
            get {
                return ResourceManager.GetString("JoinSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been created successfully..
        /// </summary>
        public static string JoinSuccessTitle {
            get {
                return ResourceManager.GetString("JoinSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your e-mail..
        /// </summary>
        public static string LoginFieldRequiredEmail {
            get {
                return ResourceManager.GetString("LoginFieldRequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pelase enter your password..
        /// </summary>
        public static string LoginFieldRequiredPassword {
            get {
                return ResourceManager.GetString("LoginFieldRequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your e-mail and password..
        /// </summary>
        public static string LoginFieldsRequired {
            get {
                return ResourceManager.GetString("LoginFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account? Sign-in..
        /// </summary>
        public static string LoginForm {
            get {
                return ResourceManager.GetString("LoginForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and start using your &lt;br /&gt;&lt;strong&gt;trial with full of features for 15 days.&lt;/strong&gt;.
        /// </summary>
        public static string LoginRegisterInfo {
            get {
                return ResourceManager.GetString("LoginRegisterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register for free.
        /// </summary>
        public static string LoginRegisterInfoLink {
            get {
                return ResourceManager.GetString("LoginRegisterInfoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter minimum of 2 (two) characters for your name/lastname..
        /// </summary>
        public static string NameMinimum {
            get {
                return ResourceManager.GetString("NameMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Found !.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For some reason the page you requested could not be found on our server..
        /// </summary>
        public static string NotFoundContent {
            get {
                return ResourceManager.GetString("NotFoundContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOMETHING JUST WENT WRONG.
        /// </summary>
        public static string NotFoundTitle {
            get {
                return ResourceManager.GetString("NotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Office 365 account is not active. Please contact your system administrator..
        /// </summary>
        public static string OfficeLoginNotActiveContent {
            get {
                return ResourceManager.GetString("OfficeLoginNotActiveContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 365 is not Active.
        /// </summary>
        public static string OfficeLoginNotActiveTitle {
            get {
                return ResourceManager.GetString("OfficeLoginNotActiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password (Again).
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be minimum 6 characters..
        /// </summary>
        public static string PasswordMinimum {
            get {
                return ResourceManager.GetString("PasswordMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New passwords do not match..
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this link was already used. Please request for a new password recovery link..
        /// </summary>
        public static string PasswordRecoveryError {
            get {
                return ResourceManager.GetString("PasswordRecoveryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now, you can login with your new password..
        /// </summary>
        public static string PasswordSuccessMessage {
            get {
                return ResourceManager.GetString("PasswordSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset successfully..
        /// </summary>
        public static string PasswordSuccessTitle {
            get {
                return ResourceManager.GetString("PasswordSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofisim.com Privacy Policy.
        /// </summary>
        public static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This e-mail has already been registered..
        /// </summary>
        public static string ProcessCodeErrorMessage {
            get {
                return ResourceManager.GetString("ProcessCodeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User exist !.
        /// </summary>
        public static string ProcessCodeErrorTitle {
            get {
                return ResourceManager.GetString("ProcessCodeErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be logged in with your Office 365 e-mail to be able to use the features..
        /// </summary>
        public static string ProcessCodeMessage {
            get {
                return ResourceManager.GetString("ProcessCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Successful.
        /// </summary>
        public static string ProcessCodeTitle {
            get {
                return ResourceManager.GetString("ProcessCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register for free now.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are required..
        /// </summary>
        public static string RegisterFieldsRequired {
            get {
                return ResourceManager.GetString("RegisterFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast registration with Office 365.
        /// </summary>
        public static string RegisterWithOffice {
            get {
                return ResourceManager.GetString("RegisterWithOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To resend the activation e-mail.
        /// </summary>
        public static string ResendMail {
            get {
                return ResourceManager.GetString("ResendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here..
        /// </summary>
        public static string ResendMailLink {
            get {
                return ResourceManager.GetString("ResendMailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation e-mail sent again..
        /// </summary>
        public static string ResendMailSuccess {
            get {
                return ResourceManager.GetString("ResendMailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to login form.
        /// </summary>
        public static string ReturnInfo {
            get {
                return ResourceManager.GetString("ReturnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast access with Office 365.
        /// </summary>
        public static string SignWithOffice {
            get {
                return ResourceManager.GetString("SignWithOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofisim.com Terms &amp; Conditions.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        public static string TR {
            get {
                return ResourceManager.GetString("TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This e-mail has already been registered..
        /// </summary>
        public static string UserExist {
            get {
                return ResourceManager.GetString("UserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account already activated..
        /// </summary>
        public static string VerifyAlreadyActivated {
            get {
                return ResourceManager.GetString("VerifyAlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail is required..
        /// </summary>
        public static string VerifyEmailRequired {
            get {
                return ResourceManager.GetString("VerifyEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We just sent you an account activation e-mail.&lt;br&gt;&lt;br&gt;&lt;span class=\&quot;spot\&quot;&gt;Please check your e-mail and follow the instructions. Your account will be activated immediately.&lt;/span&gt;.
        /// </summary>
        public static string VerifyMail {
            get {
                return ResourceManager.GetString("VerifyMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not found..
        /// </summary>
        public static string VerifyUserNotFound {
            get {
                return ResourceManager.GetString("VerifyUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail or password is invalid..
        /// </summary>
        public static string WrongInfo {
            get {
                return ResourceManager.GetString("WrongInfo", resourceCulture);
            }
        }
    }
}
